version: '3.9'
services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0
    build:
      context: ./nextapp
    volumes:
      - ./nextapp/src:/app/src
      - ./nextapp/public:/app/public
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
  nestapp:
    container_name: nestapp
    image: nestapp:1.0
    build: .
    volumes:
      - ./uploads:/app/uploads
    ports:
      - '7777:7777'
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: { }
